"""Mirror audit-layer figures and tables into each manuscript section.

Architecture decision (per user request 2026-05-17): each §6.x section folder
should be self-contained — contain every figure / table produced by the
experiments that feed it. The user will later assemble an appendix that uses
the union of all mirrored material.

Layout produced under each Results_By_Section/S06_XX/:
  paper_ready_figures/   (existing, unchanged)
  paper_ready_tables/    (existing, unchanged)
  audit_mirror/
      figures/   E0X_F0X_*.png copied 1:1 from Results_By_Experiment/
      tables/    E0X_T0X_*.csv copied 1:1
      _INDEX.md  per-file source provenance

The mapping below is fixed; running this script repeatedly is idempotent.
"""
from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path("撰写版本2/实验结果/Results_Master_Package")
EXP_ROOT = ROOT / "Results_By_Experiment"
SEC_ROOT = ROOT / "Results_By_Section"

EXP_DIR = {
    "E04": "E04_Dynamic_Evaluation",
    "E05": "E05_Regime_Specific_Evaluation",
    "E06": "E06_Internal_Control_Comparison",
    "E07": "E07_Source_of_Advantage_Decomposition",
    "E08": "E08_Heterogeneity_Ablation",
    "E09": "E09_Heterogeneity_Ladder",
    "E10": "E10_Forecast_Benchmark_Comparison",
    "E11": "E11_Training_Window_Sensitivity",
    "E12": "E12_Forecast_Horizon_and_Agent_Count_Sensitivity",
    "E13": "E13_Calibration_Method_and_Parameter_ID_Sensitivity",
}

SEC_DIR = {
    "S06_01": "S06_01_Dynamic_and_Regime_Specific_Performance",
    "S06_02": "S06_02_Internal_Controls_and_Source_of_Advantage",
    "S06_03": "S06_03_Recalibrated_Heterogeneity_Ablations",
    "S06_04": "S06_04_Forecast_Benchmark_Comparison",
    "S06_05": "S06_05_Robustness_and_Sensitivity",
}

SECTION_TO_EXPERIMENTS = {
    "S06_01": ["E04", "E05"],
    "S06_02": ["E06", "E07"],
    "S06_03": ["E08", "E09"],
    "S06_04": ["E10"],
    "S06_05": ["E11", "E12", "E13"],
}

SECTION_TITLE = {
    "S06_01": "§6.1 Dynamic and Regime-Specific Performance",
    "S06_02": "§6.2 Internal Controls and Source of Advantage",
    "S06_03": "§6.3 Recalibrated Heterogeneity Ablations",
    "S06_04": "§6.4 Forecast Benchmark Comparison",
    "S06_05": "§6.5 Robustness and Sensitivity",
}


def mirror_section(sid: str) -> tuple[int, int, list[str]]:
    sec_dir = SEC_ROOT / SEC_DIR[sid]
    out_fig = sec_dir / "audit_mirror" / "figures"
    out_tab = sec_dir / "audit_mirror" / "tables"
    out_fig.mkdir(parents=True, exist_ok=True)
    out_tab.mkdir(parents=True, exist_ok=True)

    n_fig = n_tab = 0
    rows: list[str] = []
    for eid in SECTION_TO_EXPERIMENTS[sid]:
        src_dir = EXP_ROOT / EXP_DIR[eid]
        figs = sorted((src_dir / "figures").glob("*.png"))
        tabs = sorted((src_dir / "tables").glob("*.csv"))
        for f in figs:
            shutil.copyfile(f, out_fig / f.name)
            n_fig += 1
            rows.append(f"| FIG | {eid} | `{f.name}` | `Results_By_Experiment/{EXP_DIR[eid]}/figures/{f.name}` |")
        for t in tabs:
            shutil.copyfile(t, out_tab / t.name)
            n_tab += 1
            rows.append(f"| TAB | {eid} | `{t.name}` | `Results_By_Experiment/{EXP_DIR[eid]}/tables/{t.name}` |")

    # Write provenance index
    idx = sec_dir / "audit_mirror" / "_INDEX.md"
    body = [
        f"# {sid} — Audit Mirror Index",
        "",
        f"**Section:** {SECTION_TITLE[sid]}  ",
        f"**Sourced from experiments:** {', '.join(SECTION_TO_EXPERIMENTS[sid])}  ",
        f"**Total mirrored files:** {n_fig} figures + {n_tab} tables = {n_fig + n_tab}",
        "",
        "Every file below is a verbatim copy of an audit-layer artefact under "
        "`Results_By_Experiment/`. Paper-ready versions live in this section's "
        "`paper_ready_figures/` and `paper_ready_tables/` and are *not* listed here.",
        "",
        "| Kind | Experiment | File | Source path |",
        "|---|---|---|---|",
        *rows,
        "",
        "_Index auto-generated by `_scripts/mirror_audit_to_sections.py`._",
        "",
    ]
    idx.write_text("\n".join(body), encoding="utf-8")
    return n_fig, n_tab, rows


def main():
    print("=== Mirror audit -> section ===")
    grand_fig = grand_tab = 0
    for sid in sorted(SECTION_TO_EXPERIMENTS):
        n_fig, n_tab, _ = mirror_section(sid)
        grand_fig += n_fig
        grand_tab += n_tab
        eids = ",".join(SECTION_TO_EXPERIMENTS[sid])
        print(f"  [OK] {sid}  ({eids})  figs={n_fig}  tabs={n_tab}")
    print(f"\nTOTAL: {grand_fig} figures + {grand_tab} tables mirrored.")


if __name__ == "__main__":
    main()
